const {suite,test} = require('mocha');
const assert = require('node:assert/strict');
const vscode = require('vscode');
const path = require('node:path');
const fs = require('node:fs/promises');
const os = require('node:os');

async function until(predicate, description, timeout=90000) {
 const start=Date.now();
 while(Date.now()-start<timeout) {
   const result=predicate(); if(result) return result;
   await new Promise(resolve=>setTimeout(resolve,100));
 }
 throw new Error(`Timed out: ${description}`);
}

suite('Testy in VS Code',()=>{
 test('automatically baselines, reacts to saves, retains coverage and pauses',async()=>{
  const extension=vscode.extensions.getExtension('reginaldFerland.testy');
  assert.ok(extension);
  const api=await extension.activate();
  assert.ok(api?.snapshot);
  const snapshot=()=>api.snapshot();
  await until(()=>snapshot().summary || snapshot().error,'initial baseline');
  assert.equal(snapshot().error,'',snapshot().error);
  assert.equal(snapshot().summary.tests,3);
  assert.equal(snapshot().groups.length,2);
  assert.equal(snapshot().summary.coverageAvailable,true);
  assert.match(snapshot().status,/3 passed/);
  const greeting=snapshot().coverage.find(file=>file.file.endsWith('/Greeting.cs'));
  assert.ok(greeting?.covered>0);assert.equal(greeting.stale,false);
  const root=vscode.workspace.workspaceFolders[0].uri;
  const file=vscode.Uri.joinPath(root,'ImpactDemo','Arithmetic.cs');
  const document=await vscode.workspace.openTextDocument(file);
  await vscode.window.showTextDocument(document);
  const original=document.getText();
  const replace=async text=>{
   const edit=new vscode.WorkspaceEdit();
   edit.replace(document.uri,new vscode.Range(document.positionAt(0),document.positionAt(document.getText().length)),text);
   assert.equal(await vscode.workspace.applyEdit(edit),true);
   assert.equal(await document.save(),true);
  };
  try {
   const previousPassing=snapshot().summary;
   await replace(original.replace('a + b','a + b + 0'));
   await until(()=>snapshot().summary!==previousPassing && !snapshot().running,'passing affected run');
   assert.equal(snapshot().summary.tests,2);assert.match(snapshot().status,/3 passed/,'retain the unselected Greeting outcome');
   await replace(original.replace('a + b','a + b + 1'));
   await until(()=>snapshot().summary?.failed===2 || snapshot().error,'affected failing run');
   assert.equal(snapshot().error,'',snapshot().error);
   assert.equal(snapshot().summary.files,1);assert.equal(snapshot().summary.tests,2);
   assert.deepEqual(snapshot().coverage.find(file=>file.file.endsWith('/Greeting.cs')),greeting);
   assert.match(snapshot().status,/2 failed/);
   await vscode.commands.executeCommand('testy.toggleAutoRun');
   await until(()=>snapshot().paused,'pause');
   await replace(original);
   await new Promise(resolve=>setTimeout(resolve,400));
   assert.equal(snapshot().summary.failed,2);assert.equal(snapshot().running,false);
   await vscode.commands.executeCommand('testy.toggleAutoRun');
   await until(()=>snapshot().summary?.failed===0 && !snapshot().running,'resume with queued changes');
   assert.match(snapshot().status,/3 passed/);
   await vscode.commands.executeCommand('testy.refreshTests');
   assert.equal(snapshot().summary.tests,3);assert.equal(snapshot().summary.files,2);
   const settings=vscode.workspace.getConfiguration('testy');
   let previous=snapshot().summary;
   await settings.update('runMode','all',vscode.ConfigurationTarget.Workspace);
   await until(()=>snapshot().summary!==previous && !snapshot().running,'all-mode baseline');
   previous=snapshot().summary;
   const retained=JSON.stringify(snapshot().coverage);
   await settings.update('runWithCoverage',false,vscode.ConfigurationTarget.Workspace);
   await until(()=>snapshot().summary!==previous && !snapshot().running,'coverage disabled');
   assert.equal(snapshot().summary.coverageAvailable,false);
   assert.equal(JSON.stringify(snapshot().coverage),retained,'disabling collection retains existing coverage');
   await settings.update('trigger','fileSystem',vscode.ConfigurationTarget.Workspace);
   await new Promise(resolve=>setTimeout(resolve,600));
   await until(()=>!snapshot().running && !/waiting/.test(snapshot().status),'watcher setup');
   previous=snapshot().summary;
   const generated=path.join(root.fsPath,'ImpactDemo','Ignored.g.cs');
   await fs.writeFile(generated,'// <auto-generated />\n');
   await new Promise(resolve=>setTimeout(resolve,600));
   assert.equal(snapshot().summary,previous,'generated file creation must not trigger tests');
   await fs.rm(generated);
   const header=path.join(root.fsPath,'ImpactDemo','HeaderMarked.cs');
   await fs.writeFile(header,'// <auto-generated/>\n');
   await new Promise(resolve=>setTimeout(resolve,400));
   await fs.rename(header,`${header}.renamed.cs`);
   await new Promise(resolve=>setTimeout(resolve,400));
   await fs.rm(`${header}.renamed.cs`);
   await new Promise(resolve=>setTimeout(resolve,600));
   assert.equal(snapshot().summary,previous,'observed generated headers remain excluded through rename and deletion');
   assert.equal(snapshot().running,false);
   await fs.writeFile(file.fsPath,original.replace('a + b','a + b + 1'));
   await until(()=>snapshot().summary!==previous && !snapshot().running,'external edit');
   assert.equal(snapshot().error,'',snapshot().error);
   assert.equal(snapshot().summary.files,2);assert.equal(snapshot().summary.tests,3);
   assert.equal(snapshot().summary.failed,2);
  } finally {
   if(document.getText()!==original) await replace(original);
  }
 });

 test('filesystem mode observes edits, renames and deletion of externally linked source',async()=>{
  const api=await vscode.extensions.getExtension('reginaldFerland.testy').activate(), snapshot=()=>api.snapshot();
  const root=vscode.workspace.workspaceFolders[0].uri.fsPath, settings=vscode.workspace.getConfiguration('testy');
  await until(()=>!snapshot().running && !/waiting/.test(snapshot().status),'previous run to settle');
  let previous=snapshot().summary;
  await settings.update('runMode','affected',vscode.ConfigurationTarget.Workspace);
  await settings.update('runWithCoverage',true,vscode.ConfigurationTarget.Workspace);
  await until(()=>snapshot().summary!==previous && !snapshot().running,'affected baseline');
  assert.equal(snapshot().error,'',snapshot().error);
  const external=await fs.mkdtemp(path.join(os.tmpdir(),'testy linked '));
  const source=path.join(root,'ImpactDemo','Arithmetic.cs'),project=path.join(root,'ImpactDemo','ImpactDemo.csproj');
  const original=await fs.readFile(source,'utf8'),originalProject=await fs.readFile(project,'utf8');
  let linked=path.join(external,'Arithmetic.cs');
  const include=file=>originalProject.replace('</Project>',`<ItemGroup><Compile Include="${file.replace(/&/g,'&amp;').replace(/"/g,'&quot;')}" Link="Arithmetic.cs" /></ItemGroup></Project>`);
  try{
   previous=snapshot().summary;
   await fs.rename(source,linked);await fs.writeFile(project,include(linked));
   await until(()=>snapshot().summary!==previous && !snapshot().running,'linked source baseline');
   assert.equal(snapshot().error,'',snapshot().error);
   await new Promise(resolve=>setTimeout(resolve,500));
   previous=snapshot().summary;await fs.writeFile(linked,original.replace('a + b','a + b + 1'));
   await until(()=>snapshot().summary!==previous && !snapshot().running,'external linked edit');
   assert.equal(snapshot().summary.tests,2);assert.equal(snapshot().summary.failed,2);
   previous=snapshot().summary;
   const renamed=path.join(external,'Renamed.cs');await fs.rename(linked,renamed);linked=renamed;
   await fs.writeFile(project,include(linked));await fs.writeFile(linked,original);
   await until(()=>snapshot().summary!==previous && !snapshot().running,'linked source rename');
   assert.equal(snapshot().error,'',snapshot().error);assert.equal(snapshot().summary.failed,0);
   await fs.rm(linked);await until(()=>snapshot().error && !snapshot().running,'linked source deletion build error');
   assert.match(snapshot().error,/Building|could not be found|not found/);
   await fs.writeFile(linked,original);await until(()=>!snapshot().error && !snapshot().running,'recreated linked source');
   assert.match(snapshot().status,/3 passed/);
  }finally{
   await settings.update('autoRun',false,vscode.ConfigurationTarget.Workspace);
   await until(()=>snapshot().paused && !snapshot().running,'pause before fixture cleanup');
   await fs.writeFile(project,originalProject);await fs.writeFile(source,original);await fs.rm(external,{recursive:true,force:true});
  }
 });
});
