const {suite,test} = require('mocha');
const assert = require('node:assert/strict');
const vscode = require('vscode');
const path = require('node:path');
const fs = require('node:fs/promises');

async function until(predicate, description, timeout=90000) {
 const start=Date.now();
 while(Date.now()-start<timeout) {
   const result=predicate(); if(result) return result;
   await new Promise(resolve=>setTimeout(resolve,100));
 }
 throw new Error(`Timed out: ${description}`);
}

suite('Testy in VS Code',()=>{
 test('automatically baselines, reacts to saves, retains coverage and pauses',async()=>{
  const extension=vscode.extensions.getExtension('reginaldFerland.testy');
  assert.ok(extension);
  const api=await extension.activate();
  assert.ok(api?.snapshot);
  const snapshot=()=>api.snapshot();
  await until(()=>snapshot().summary || snapshot().error,'initial baseline');
  assert.equal(snapshot().error,'',snapshot().error);
  assert.equal(snapshot().summary.tests,3);
  assert.equal(snapshot().groups.length,2);
  assert.equal(snapshot().summary.coverageAvailable,true);
  assert.match(snapshot().status,/3 passed/);
  const greeting=snapshot().coverage.find(file=>file.file.endsWith('/Greeting.cs'));
  assert.ok(greeting?.covered>0);assert.equal(greeting.stale,false);
  const root=vscode.workspace.workspaceFolders[0].uri;
  const file=vscode.Uri.joinPath(root,'ImpactDemo','Arithmetic.cs');
  const document=await vscode.workspace.openTextDocument(file);
  await vscode.window.showTextDocument(document);
  const original=document.getText();
  const replace=async text=>{
   const edit=new vscode.WorkspaceEdit();
   edit.replace(document.uri,new vscode.Range(document.positionAt(0),document.positionAt(document.getText().length)),text);
   assert.equal(await vscode.workspace.applyEdit(edit),true);
   assert.equal(await document.save(),true);
  };
  try {
   await replace(original.replace('a + b','a + b + 1'));
   await until(()=>snapshot().summary?.failed===2 || snapshot().error,'affected failing run');
   assert.equal(snapshot().error,'',snapshot().error);
   assert.equal(snapshot().summary.files,1);assert.equal(snapshot().summary.tests,2);
   assert.deepEqual(snapshot().coverage.find(file=>file.file.endsWith('/Greeting.cs')),greeting);
   assert.match(snapshot().status,/2 failed/);
   await vscode.commands.executeCommand('testy.toggleAutoRun');
   await until(()=>snapshot().paused,'pause');
   await replace(original);
   await new Promise(resolve=>setTimeout(resolve,400));
   assert.equal(snapshot().summary.failed,2);assert.equal(snapshot().running,false);
   await vscode.commands.executeCommand('testy.toggleAutoRun');
   await until(()=>snapshot().summary?.failed===0 && !snapshot().running,'resume with queued changes');
   assert.match(snapshot().status,/3 passed/);
   await vscode.commands.executeCommand('testy.refreshTests');
   assert.equal(snapshot().summary.tests,3);assert.equal(snapshot().summary.files,2);
   const settings=vscode.workspace.getConfiguration('testy');
   let previous=snapshot().summary;
   await settings.update('runMode','all',vscode.ConfigurationTarget.Workspace);
   await until(()=>snapshot().summary!==previous && !snapshot().running,'all-mode baseline');
   previous=snapshot().summary;
   const retained=JSON.stringify(snapshot().coverage);
   await settings.update('runWithCoverage',false,vscode.ConfigurationTarget.Workspace);
   await until(()=>snapshot().summary!==previous && !snapshot().running,'coverage disabled');
   assert.equal(snapshot().summary.coverageAvailable,false);
   assert.equal(JSON.stringify(snapshot().coverage),retained,'disabling collection retains existing coverage');
   await settings.update('trigger','fileSystem',vscode.ConfigurationTarget.Workspace);
   await new Promise(resolve=>setTimeout(resolve,600));
   await until(()=>!snapshot().running && !/waiting/.test(snapshot().status),'watcher setup');
   previous=snapshot().summary;
   const generated=path.join(root.fsPath,'ImpactDemo','Ignored.g.cs');
   await fs.writeFile(generated,'// <auto-generated />\n');
   await new Promise(resolve=>setTimeout(resolve,600));
   assert.equal(snapshot().summary,previous,'generated file creation must not trigger tests');
   await fs.rm(generated);
   await fs.writeFile(file.fsPath,original.replace('a + b','a + b + 1'));
   await until(()=>snapshot().summary!==previous && !snapshot().running,'external edit');
   assert.equal(snapshot().error,'',snapshot().error);
   assert.equal(snapshot().summary.files,2);assert.equal(snapshot().summary.tests,3);
   assert.equal(snapshot().summary.failed,2);
  } finally {
   if(document.getText()!==original) await replace(original);
  }
 });
});
