import * as path from 'node:path';
import { realpathSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { minimatch } from 'minimatch';

export const defaultExcludes = [
    '**/bin/**', '**/obj/**', '**/TestResults/**', '**/node_modules/**', '**/.git/**',
    '**/.testy/**', '**/*.g.cs', '**/*.g.i.cs', '**/*.generated.cs', '**/*.designer.cs'
] as const;

export function normalizePath(file: string): string {
    // PDBs and MSBuild may spell the same path through different symlink aliases
    // (notably /var and /private/var on macOS). Preserve that identity for new or
    // deleted files by resolving their nearest existing ancestor as well.
    let parent = path.resolve(file);
    const missing: string[] = [];
    for (;;) {
        try { parent = path.join(realpathSync.native(parent), ...missing); break; }
        catch {
            const next = path.dirname(parent);
            if (next === parent) { parent = path.resolve(file); break; }
            missing.unshift(path.basename(parent)); parent = next;
        }
    }
    const normalized = parent.replace(/\\/g, '/');
    return process.platform === 'win32' ? normalized.toLowerCase() : normalized;
}

/** Scope this cache to one discovery/run so filesystem changes cannot outlive it. */
export function pathNormalizer(): (file: string) => string {
    const paths = new Map<string, string>();
    return file => {
        let normalized = paths.get(file);
        if (normalized === undefined) {normalized = normalizePath(file); paths.set(file, normalized);}
        return normalized;
    };
}

export function isInside(file: string, folder: string): boolean {
    const relative = path.relative(folder, file);
    return relative === '' || (!relative.startsWith(`..${path.sep}`) && relative !== '..' && !path.isAbsolute(relative));
}

export function matchesPattern(file: string, pattern: string, roots: readonly string[] = []): boolean {
    const directory = /[/\\]$/.test(file);
    const candidates = [file, ...roots.filter(root => isInside(file, root)).map(root => path.relative(root, file) + (directory ? '/' : ''))];
    return candidates.some(candidate => minimatch(candidate.replace(/\\/g, '/'), pattern, { dot: true, nocase: true }));
}

export function isExcluded(file: string, excludes: readonly string[] = defaultExcludes, roots: readonly string[] = []): boolean {
    return excludes.some(pattern => matchesPattern(file, pattern, roots));
}

export function contentHash(content: string | Buffer): string {
    return createHash('sha256').update(content).digest('hex');
}

/** Decode the BOM encodings used by C# sources without changing the input bytes. */
export function sourceText(bytes: Buffer): string {
    if (bytes[0] === 0xff && bytes[1] === 0xfe) {return bytes.subarray(2).toString('utf16le');}
    if (bytes[0] === 0xfe && bytes[1] === 0xff) {
        return Buffer.from(bytes.subarray(2, bytes.length - bytes.length % 2)).swap16().toString('utf16le');
    }
    return bytes.subarray(bytes[0] === 0xef && bytes[1] === 0xbb && bytes[2] === 0xbf ? 3 : 0).toString('utf8');
}

export function isGeneratedSource(file: string, content: string | Buffer): boolean {
    // Production save/disk events and source tracking use the same byte prefix.
    // A supplied string represents UTF-8 text, without an on-disk encoding.
    const prefix = Buffer.isBuffer(content) ? content.subarray(0, 2048) : Buffer.from(content.slice(0, 2048)).subarray(0, 2048);
    if (!/\.cs$/i.test(file)) {return false;}
    let remaining = sourceText(prefix).trimStart();
    // Only leading comments can declare a generated header. Marker strings in
    // generator tests, or prose mentioning a marker, are ordinary source.
    while (remaining.startsWith('//') || remaining.startsWith('/*')) {
        const line = remaining.startsWith('//');
        const end = line ? remaining.indexOf('\n') : remaining.indexOf('*/', 2);
        const comment = remaining.slice(2, end < 0 ? undefined : end);
        if (comment.split(/\r?\n/).some(text => /^\s*[*\/]?\s*<auto-generated\b/i.test(text))) {return true;}
        if (end < 0) {return false;}
        remaining = remaining.slice(end + (line ? 1 : 2)).trimStart();
    }
    return false;
}

/** Missing dependencies are versions too: their later creation invalidates a trace. */
export function sourceVersion(hashes: ReadonlyMap<string, string>, file: string): string { return hashes.get(file) ?? '<missing>'; }

export function testFileId(project: string, framework: string, file?: string, normalize = normalizePath): string {
    return contentHash(`${normalize(project)}\0${framework}\0${file ? normalize(file) : '<unknown>'}`);
}

/** Inputs are already canonical paths from project evaluation. */
export function testTargetKey(project: string, framework: string): string {
    return `${project}\0${framework}`;
}

export function isConfigurationFile(file: string): boolean {
    return /\.(csproj|sln|slnx|props|targets|runsettings|json|config|resx|editorconfig|globalconfig|ruleset)$/i.test(file);
}

export function isCompilerConfiguration(file: string): boolean { return /\.(editorconfig|globalconfig|ruleset)$/i.test(file); }

export function isInheritedConfiguration(file: string): boolean {
    return isCompilerConfiguration(file) || path.basename(file).toLowerCase() === 'global.json';
}

/** Inherited configs above a workspace must not turn its ancestors into source roots. */
export function sourceDirectories(files: readonly string[], directories: readonly string[]): readonly string[] {
    const configs = new Set<string>(), sources = new Set<string>();
    for (const file of files) {(isInheritedConfiguration(file) ? configs : sources).add(path.dirname(file));}
    return directories.filter(directory => !configs.has(directory) || sources.has(directory));
}
