const {test}=require('node:test');
const assert=require('node:assert/strict');
const path=require('node:path');
const fs=require('node:fs');
const vm=require('node:vm');
const {createRequire}=require('node:module');
const {EventEmitter}=require('node:events');
const {PassThrough}=require('node:stream');
const {requestTests,testResult}=require('../../out/services/mtp');

test('MTP transport preserves explicit retry outcomes and rejects inconsistent failure exits',async()=>{
 const options={dotnet:process.execPath,assembly:path.resolve('test/fixtures/mtp-peer.cjs'),cwd:process.cwd(),timeoutMs:5000};
 const updates=[{uid:'row','execution-state':'failed','error.message':'old','retry.attempt':1,'retry.is-superseded':true},
  {uid:'row','execution-state':'passed','retry.attempt':2,'retry.is-superseded':false}];
 const nodes=await requestTests({...options,env:{TESTY_UPDATES:JSON.stringify(updates)}},'run');
 assert.equal(testResult(nodes[0]).outcome,'passed');assert.equal(testResult(nodes[0]).message,undefined);
 await assert.rejects(requestTests({...options,env:{TESTY_UPDATES:JSON.stringify([{uid:'row','execution-state':'passed'}]),TESTY_EXIT:'2'}},'run'),/cannot be reported as passing/);
 await assert.rejects(requestTests({...options,env:{TESTY_UPDATES:JSON.stringify([{uid:'suite','node-type':'group','execution-state':'failed'}])}},'run'),/test group failed/);
 const runtime=await requestTests({...options,env:{TESTY_UPDATES:JSON.stringify([{uid:'only-at-runtime','execution-state':'passed','location.file':'/workspace/Test.cs','location.type':'Tests','location.method':'Theory'}])}},'run',[{uid:'parent','location.type':'Tests','location.method':'Theory'}]);
 assert.equal(runtime[0].uid,'only-at-runtime');assert.ok(testResult(runtime[0]).node);
});

test('MTP reports timeouts and early process exits instead of RPC disposal errors',async()=>{
 const options={dotnet:process.execPath,assembly:path.resolve('test/fixtures/mtp-peer.cjs'),cwd:process.cwd(),timeoutMs:500};
 await assert.rejects(requestTests({...options,env:{TESTY_HANG:'1'}},'run'),/exceeded its time limit/);
 await assert.rejects(requestTests({...options,timeoutMs:5000,env:{TESTY_EXIT_DURING:'41'}},'run'),/exit 41.*\ncontrolled process failure/);
});

function uiPrototype(vscode={}) {
 const file=path.resolve('out/extension.js'), realRequire=createRequire(file), exports={};
 vm.runInNewContext(fs.readFileSync(file,'utf8')+'\nexports.Testy=Testy;',{
  exports,require:name=>name==='vscode'?vscode:name==='./configuration'?{}:realRequire(name),Buffer,setTimeout,clearTimeout
 });
 return exports.Testy.prototype;
}

test('generated deletions retain classification while ordinary recreations trigger testing',async t=>{
 const io=require('node:fs/promises'),{SourceTracker}=require('../../out/services/sources'),{normalizePath}=require('../../out/core/paths');
 const root=normalizePath(await io.mkdtemp(path.join(require('node:os').tmpdir(),'testy-generated-events-')));
 t.after(()=>io.rm(root,{recursive:true,force:true}));
 const file=normalizePath(path.join(root,'Stamped.cs')),sources=new SourceTracker(),requests=[],proto=uiPrototype();
 await io.writeFile(file,'// <auto-generated/>\nclass Stamped {}');sources.setFiles([file]);await sources.refresh([file]);
 const context={roots:[root],generatedFiles:new Set(),config:{pattern:'**/*.cs',excludes:[]},engine:{knownFiles:[file],directories:[root],sources,markChanged:async()=>{}},scheduler:{request:(...args)=>requests.push(args)}};
 const uri={scheme:'file',fsPath:file};
 await proto.changed.call(context,uri);await io.rm(file);await proto.changed.call(context,uri,undefined,true);
 await sources.refresh([file]);assert.equal(sources.isGenerated(file),true);
 await proto.changed.call(context,uri,undefined,true);assert.equal(requests.length,0);
 await io.writeFile(file,'class Ordinary {}');await proto.changed.call(context,uri);
 await sources.refresh([file]);assert.equal(requests.length,1);assert.equal(sources.isGenerated(file),false);assert.ok(sources.hashes.has(file));
 const created={scheme:'file',fsPath:path.join(root,'NewGenerated.cs')},renamed={scheme:'file',fsPath:path.join(root,'RenamedGenerated.cs')};
 await io.writeFile(created.fsPath,'// <auto-generated/>');await proto.changed.call(context,created);
 await io.rename(created.fsPath,renamed.fsPath);await proto.changed.call(context,created,undefined,true);await proto.changed.call(context,renamed,undefined,true);
 await io.rm(renamed.fsPath);await proto.changed.call(context,renamed,undefined,true);
 assert.equal(requests.length,1,'creation, rename and deletion before the next baseline retain the observed header');
});

test('Windows assembly matching instruments mixed-case output names',async()=>{
 const file=path.resolve('out/services/runner.js'),realRequire=createRequire(file),exports={};
 const io={readdir:async()=>['Product.dll','Tests.dll','External.dll'].map(name=>({name,isDirectory:()=>false,isFile:()=>true}))};
 vm.runInNewContext(fs.readFileSync(file,'utf8')+'\nexports.workspaceOutputs=workspaceOutputs;exports.assemblyName=assemblyName;',{
  exports,process:{platform:'win32'},require:name=>name==='node:fs/promises'?io:realRequire(name)
 });
 const selected=await exports.workspaceOutputs('/output',new Set(['product.dll','tests.dll'].map(exports.assemblyName)));
 assert.deepEqual([...selected].map(file=>path.basename(file)),['Product.dll','Tests.dll']);
});

test('watchers cover external sources, reuse unchanged roots and dispose removed roots',()=>{
 const patterns=[];let disposed=0;
 const proto=uiPrototype({RelativePattern:class {constructor(base,pattern){Object.assign(this,{base,pattern});}},workspace:{createFileSystemWatcher:pattern=>{
  patterns.push(pattern);return{dispose(){disposed++;},onDidChange(){},onDidCreate(){},onDidDelete(){}};
 }}});
 const context={watchers:[],roots:['/workspace'],config:{trigger:'fileSystem',pattern:'**/*.cs'},engine:{inputVersion:0,knownFiles:[],directories:['/workspace/Tests','/linked/src','/linked','/other']}};
 proto.watch.call(context);assert.equal(patterns.length,3);assert.deepEqual(patterns.slice(1).map(p=>p.base),['/other','/linked']);
 proto.watch.call(context);assert.equal(patterns.length,3,'unchanged discovery must not recreate watchers');
 context.engine.inputVersion++;context.engine.directories=['/workspace/Tests','/linked'];proto.watch.call(context);assert.equal(disposed,3);assert.equal(patterns.length,5);
 context.config.trigger='save';proto.watch.call(context);assert.equal(disposed,5);assert.equal(context.watchers.length,0);
});

test('save invalidation preserves historical test outcomes until final selection',async()=>{
 const proto=uiPrototype();let invalidated=0,cleared=0;
 const context={disposed:false,roots:['/workspace'],generatedFiles:new Set(),config:{excludes:[],pattern:'**/*.cs'},
  engine:{knownFiles:['/workspace/Code.cs'],markChanged:async()=>{}},scheduler:{request(){}},
  controller:{invalidateTestResults(){invalidated++;}},setOutcome(){cleared++;}};
 await proto.changed.call(context,{scheme:'file',fsPath:'/workspace/Code.cs'},'class Code {}');
 assert.equal(invalidated,0);assert.equal(cleared,0);
});

test('coverage publication sends only changed line data and a fresh snapshot per run',()=>{
 let calls=0;
 const proto=uiPrototype({Uri:{file:fsPath=>({fsPath})},FileCoverage:class {},window:{visibleTextEditors:[]}});
 const lines=[{line:1,hits:1}],summary={file:'/Code.cs',covered:1,total:1,stale:false,lines,groupIds:['one']};
 let summaries=[summary];
 const context={disposed:false,engine:{coverage:{summarize:()=>summaries},hashes:new Map()},productionSources:new Set(['/Code.cs']),
  publishedCoverage:new Map(),details:new WeakMap(),activeRun:{addCoverage(){calls++;}},queueDecorations(){},updateStatus(){}};
 proto.publishCoverage.call(context);proto.publishCoverage.call(context);assert.equal(calls,1);
 summaries=[{...summary,groupIds:['one','two']}];proto.publishCoverage.call(context);assert.equal(calls,1,'new attribution with identical line data needs no UI publication');
 summaries=[{...summary,covered:0,lines:[{line:1,hits:0}]}];proto.publishCoverage.call(context);assert.equal(calls,2);
 context.publishedCoverage.clear();proto.publishCoverage.call(context);assert.equal(calls,3,'each run needs its retained snapshot');
 context.activeRun=undefined;context.publishedCoverage.clear();proto.publishCoverage.call(context);assert.equal(calls,3,'do not allocate publications outside a run');
});

test('save-mode directory events expand known paths and trigger structural discovery',async()=>{
 const proto=uiPrototype(), requested=[], marked=[];
 const {normalizePath}=require('../../out/core/paths');
 const root=normalizePath(path.resolve(require('node:os').tmpdir(),'testy-ui-workspace'));
 const directory=path.join(root,'Tests','Feature'),source=normalizePath(path.join(directory,'FeatureTests.cs'));
 const context={disposed:false,roots:[root],config:{excludes:[],pattern:'**/*.{cs,csproj}',mode:'affected'},
  engine:{knownFiles:[source],select:()=>({groups:[]}),markChanged:async files=>marked.push([...files])},
  scheduler:{request:(files,full)=>requested.push({files:[...files],full})},controller:{invalidateTestResults:()=>{}},items:new Map()};
 await proto.changed.call(context,{scheme:'file',fsPath:directory},undefined,true);
 assert.equal(requested.length,1);assert.equal(requested[0].full,true);
 assert.deepEqual(requested[0].files,[source,normalizePath(directory)]);
 assert.deepEqual(marked[0],requested[0].files);
});

test('runtime-only result IDs are registered and selected for manual reruns',async()=>{
 const proto=uiPrototype();let selected;
 const item={id:'file:runtime',children:{forEach:()=>{}}};
 const context={disposed:false,items:new Map([['file:runtime',item]]),testIds:new Map(),treeFiles:new Map(),setOutcome:()=>{},updateStatus:()=>{},
  scheduler:{runManual:async callback=>callback(new AbortController().signal)},bindCancellation:()=>({controller:new AbortController(),dispose:()=>{}}),
  execute:async(_batch,_signal,_request,selection)=>selected=selection};
 proto.publishResult.call(context,{id:'file',file:'/workspace/Test.cs'},{id:'runtime',name:'Runtime case',outcome:'passed'});
 await proto.manual.call(context,{include:[item]},{},false);
 assert.equal(selected.groups.has('file'),true);assert.equal(selected.tests.get('file').has('runtime'),true);
});

test('unresolved runtime and ambiguous row identities expand to fresh containing-file nodes',async()=>{
 const file=path.resolve('out/services/runner.js'),realRequire=createRequire(file),exports={};let sent,expanded;
 const mtp=realRequire('./mtp');
 vm.runInNewContext(fs.readFileSync(file,'utf8'),{exports,require:name=>name==='./mtp'?{...mtp,requestTests:async(_options,_operation,nodes)=>{
  sent=nodes;return nodes.map(node=>({...node,'execution-state':'passed'}));
 }}:realRequire(name)});
 const nodes=[{uid:'one','display-name':'duplicate'},{uid:'two','display-name':'duplicate'},{uid:'other','display-name':'other'}];
 const project={project:'/Tests.csproj',assembly:'/Tests.dll',framework:'net10.0'};
 const group={...project,id:'file',file:'/Tests.cs',tests:nodes.slice(0,2).map(mtp.discoveredTest)};
 const other={...project,id:'other-file',file:'/Other.cs',tests:[mtp.discoveredTest(nodes[2])]};
 const session=new exports.RunnerSession({dotnet:'dotnet',storage:'.',testArguments:[],onExpanded:groups=>expanded=groups});
 const byKey=new Map([[JSON.stringify(['duplicate',null,null,null]),nodes.slice(0,2)]]);
 session.prepared.set(`${group.project}\0${group.framework}`,{root:'.',output:{directory:'.',restore:async()=>{}},session:'fake',coverage:false,nodes,
  nativeById:new Map(nodes.map(node=>[node.uid,node])),byKey,groups:[group,other],runs:0});
 for(const name of ['runtime only','duplicate']){
  const result=await session.run([{...group,tests:[mtp.discoveredTest({uid:'old-runtime-id','display-name':name})]}],new Map());
  assert.deepEqual([...sent].map(node=>node.uid),['one','two']);
  assert.equal(expanded.length,1);assert.equal(expanded[0].id,'file');
  assert.equal(result.executedGroups[0].tests.length,2);assert.equal(result.results.length,2);
 }
 // No real output or worker was created by this controlled preparation.
 session.prepared.clear();await session.dispose();
});

test('Windows fallback cancellation waits for taskkill completion before releasing the owned run',async()=>{
 const file=path.resolve('out/services/process.js'), exports={}, processes=[];
 function spawn(command,args) {
  const child=new EventEmitter();Object.assign(child,{pid:100,stdout:new PassThrough(),stderr:new PassThrough(),kill:()=>{}});
  processes.push({command,args,child});return child;
 }
 vm.runInNewContext(fs.readFileSync(file,'utf8'),{exports,require:name=>name==='node:child_process'?{spawn}:createRequire(file)(name),__dirname:path.dirname(file),process:{platform:'win32',env:{}},setTimeout,clearTimeout});
 const abort=new AbortController(), owned=exports.startProcess('dotnet',['test'],{cwd:'.',signal:abort.signal});
 let settled=false;const done=owned.done.catch(error=>{settled=true;assert.equal(error.name,'AbortError');});
 abort.abort();assert.equal(processes[1].command,'taskkill');assert.ok(processes[1].args.includes('/T'));
 processes[0].child.emit('close',1);await Promise.resolve();assert.equal(settled,false);
 processes[1].child.emit('close',0);await done;assert.equal(settled,true);
});

test('Windows owned processes receive cancellation through the job host before forced fallback',async()=>{
 const file=path.resolve('out/services/process.js'),exports={},processes=[],writes=[];
 function spawn(command,args){
  const child=new EventEmitter();const stdin=new EventEmitter();Object.assign(stdin,{writable:true,write:value=>writes.push(value)});
  Object.assign(child,{pid:100,stdin,stdout:new PassThrough(),stderr:new PassThrough(),kill(){}});processes.push({command,args,child});return child;
 }
 vm.runInNewContext(fs.readFileSync(file,'utf8'),{exports,require:name=>name==='node:child_process'?{spawn}:createRequire(file)(name),__dirname:path.dirname(file),process:{platform:'win32',env:{}},setTimeout,clearTimeout});
 const abort=new AbortController(),owned=exports.startProcess('a tool.exe',['argument with spaces'],{cwd:'.',signal:abort.signal,dotnetHost:'custom-dotnet.exe'});
 assert.equal(processes[0].command,'custom-dotnet.exe');assert.match(processes[0].args[0],/Testy.ProcessHost.dll$/);
 assert.deepEqual([...processes[0].args.slice(1)],['a tool.exe','argument with spaces']);
 abort.abort();assert.deepEqual(writes,['cancel\n']);assert.equal(processes.length,1);
 processes[0].child.emit('close',1);await assert.rejects(owned.done,{name:'AbortError'});
});

test('a complete MTP stream cannot hide unfinished or missing test outcomes',async()=>{
 const options={dotnet:process.execPath,assembly:path.resolve('test/fixtures/mtp-peer.cjs'),timeoutMs:5000};
 const expected=[{uid:'first','location.type':'Tests','location.method':'First'},{uid:'second','location.type':'Tests','location.method':'Second'}];
 const passed={...expected[0],'execution-state':'passed'};
 for(const updates of [[passed,{...expected[1],'execution-state':'in-progress'}],[passed]]){
  const seen=[];
  await assert.rejects(requestTests({...options,expectedTests:expected,onNode:node=>seen.push(node),env:{TESTY_UPDATES:JSON.stringify(updates)}},'run'),/Incomplete test run/);
  assert.ok(seen.some(node=>testResult(node)?.outcome==='passed'),'completed results remain visible');
  assert.ok(seen.some(node=>node.uid==='second' && testResult(node)?.outcome==='errored'),'missing outcome is visible as an error');
 }
 const deferred=[{uid:'parent','location.type':'Tests','location.method':'Theory'}];
 const updates=[{...deferred[0],'execution-state':'in-progress'},{uid:'row','location.type':'Tests','location.method':'Theory','execution-state':'passed'}];
 assert.equal((await requestTests({...options,expectedTests:deferred,env:{TESTY_UPDATES:JSON.stringify(updates)}},'run')).length,2);
});


test('runtime rows cannot conceal another unfinished row or ambiguously replace several discovered cases',()=>{
 const {assertComplete}=require('../../out/services/mtp');
 const identity={'location.type':'Tests','location.method':'Theory'};
 assert.throws(()=>assertComplete([{uid:'new-pass',...identity,'execution-state':'passed'},{uid:'new-running',...identity,'execution-state':'in-progress'}],[{uid:'parent',...identity}]),/Incomplete/);
 assert.throws(()=>assertComplete([{uid:'new-pass',...identity,'execution-state':'passed'}],[{uid:'first',...identity},{uid:'second',...identity}]),/Incomplete/);
});

test('manual UI captures containers without freezing their old child IDs',async()=>{
 const proto=uiPrototype();let selection;
 const leaf={id:'leaf',children:{forEach:()=>{}}},file={id:'file:g',children:{forEach:callback=>callback(leaf)}},project={id:'project:/Tests.csproj',children:{forEach:callback=>callback(file)}};
 const context={testIds:new Map([['leaf',{group:'g',test:'old'}]]),bindCancellation:()=>({controller:new AbortController(),dispose(){}}),
  scheduler:{runManual:async callback=>callback(new AbortController().signal)},execute:async(_batch,_signal,_request,manual)=>selection=manual,reportError:error=>{throw error;}};
 await proto.manual.call(context,{include:[file],exclude:[leaf]}, {},false);
 assert.equal(selection.groups.has('g'),true);assert.equal(selection.tests.has('g'),false);assert.equal(selection.exclude.tests.get('g').has('old'),true);
 await proto.manual.call(context,{include:[project]}, {},false);assert.equal(selection.projects.has('/Tests.csproj'),true);
 await proto.manual.call(context,{}, {},false);assert.equal(selection.all,true);
});

test('save mode never plans watchers and unchanged filesystem discovery never reads input paths',()=>{
 let reads=0,created=0;
 const proto=uiPrototype({RelativePattern:class {},workspace:{createFileSystemWatcher(){created++;return{dispose(){},onDidChange(){},onDidCreate(){},onDidDelete(){}};}}});
 const engine={inputVersion:1,get knownFiles(){reads++;return ['/workspace/Tests.cs'];},get directories(){reads++;return ['/workspace'];}};
 const context={watchers:[],roots:['/workspace'],config:{trigger:'save',pattern:'**/*.cs'},engine};
 for(let i=0;i<10;i++)proto.watch.call(context);
 assert.equal(reads,0);assert.equal(created,0);
 context.config.trigger='fileSystem';proto.watch.call(context);assert.equal(reads,2);assert.equal(created,1);
 for(let i=0;i<10;i++)proto.watch.call(context);assert.equal(reads,2);assert.equal(created,1);
 engine.inputVersion++;proto.watch.call(context);assert.equal(reads,4);assert.equal(created,2);
});

test('status context commands are emitted only for pause state changes',()=>{
 const values=[],proto=uiPrototype({commands:{executeCommand:(_command,_key,value)=>values.push(value)}});
 const context={engine:{groups:[]},scheduler:{isPaused:false},passed:0,failed:0,status:{}};
 for(let i=0;i<20000;i++)proto.updateStatus.call(context);
 context.scheduler.isPaused=true;proto.updateStatus.call(context);proto.updateStatus.call(context);
 assert.deepEqual(values,[false,true]);
});

test('MTP output is published once across metadata updates while preserving rows, retries and pre-terminal output',async()=>{
 const output=[],proto=uiPrototype();
 const context={testIds:new Map(),treeFiles:new Map(),items:new Map([['g:row',{}]]),setOutcome(){},updateStatus(){},activeRun:{passed(){},appendOutput:text=>output.push(text)}};
 const updates=[{uid:'row','execution-state':'in-progress',standardOutput:'before '},
  {uid:'row','execution-state':'passed',standardOutput:'done\n'}, {uid:'row','time.duration-ms':12},
  {uid:'row','execution-state':'passed',standardOutput:'same row text\n'},
  {uid:'row','execution-state':'passed','retry.attempt':2,standardOutput:'same row text\n'},
  {uid:'row','time.duration-ms':25}];
 await requestTests({dotnet:process.execPath,assembly:path.resolve('test/fixtures/mtp-peer.cjs'),cwd:process.cwd(),timeoutMs:5000,
  env:{TESTY_UPDATES:JSON.stringify(updates)},onNode:node=>{const result=testResult(node);if(result)proto.publishResult.call(context,{id:'g'},result);}},'run');
 assert.deepEqual(output,['before done\r\n','same row text\r\n','same row text\r\n']);
});

test('runtime fallback honors explicit exclusions and rejects unselectable runtime exclusions',async()=>{
 const file=path.resolve('out/services/runner.js'),realRequire=createRequire(file),exports={},mtp=realRequire('./mtp');let sent;
 const nodes=[{uid:'parent','display-name':'Theory'},{uid:'excluded','display-name':'Other'}];
 vm.runInNewContext(fs.readFileSync(file,'utf8'),{exports,require:name=>name==='./mtp'?{...mtp,requestTests:async(_options,_operation,selected)=>{
  sent=selected??nodes;return sent.map(node=>({...node,'execution-state':'passed'}));
 }}:realRequire(name)});
 const group={id:'g',project:'/Tests.csproj',assembly:'/Tests.dll',framework:'net10.0',file:'/Tests.cs',tests:nodes.map(mtp.discoveredTest)};
 const runtime=mtp.discoveredTest({uid:'runtime','display-name':'Theory(1)'});
 const {selectManual}=require('../../out/services/engine');
 const session=new exports.RunnerSession({dotnet:'dotnet',storage:'.',testArguments:[]});
 session.prepared.set(`${group.project}\0${group.framework}`,{root:'.',output:{directory:'.',restore:async()=>{}},session:'fake',coverage:false,nodes,
  nativeById:new Map(nodes.map(node=>[node.uid,node])),byKey:new Map(),groups:[group],runs:0});
 const select=id=>selectManual([group],{groups:new Set(['g']),exclude:{groups:new Set(['g']),tests:new Map([['g',new Set([id])]])}},()=>[...group.tests,runtime]);
 const result=await session.run(select('excluded'),new Map());
 assert.deepEqual([...sent].map(node=>node.uid),['parent']);assert.equal(result.executedGroups[0].tests.length,1);
 sent=undefined;await assert.rejects(session.run(select('runtime'),new Map()),/cannot honor an exclusion/);assert.equal(sent,undefined);
 session.prepared.clear();await session.dispose();
});

test('startup schedules its baseline after optional cache failure, but never after cancellation',async t=>{
 const {TestEngine}=require('../../out/services/engine'),proto=uiPrototype(),requested=[];
 const io=require('node:fs/promises'),storage=await io.mkdtemp(path.join(require('node:os').tmpdir(),'testy-cache-failure-'));
 t.after(()=>io.rm(storage,{recursive:true,force:true}));
 const warnings=[],engine=new TestEngine({roots:[],storage,events:{output:text=>warnings.push(text)}});
 engine.cache.restore=async()=>{throw new Error('unavailable cache worker');};
 const lifetime=new AbortController(),context={engine,lifetime,config:{enabled:true},watch(){},scheduler:{setPaused(){},request:(...args)=>requested.push(args)}};
 await proto.start.call(context);assert.equal(requested.length,1);assert.equal(requested[0][1],true);assert.match(warnings[0],/fresh baseline/);
 lifetime.abort();await assert.rejects(proto.start.call(context),{name:'AbortError'});assert.equal(requested.length,1);
});

test('editor coverage refresh yields during shared-file aggregation and never falls back to synchronous reads',async()=>{
 const {CoverageStore}=require('../../out/core/coverage'),{normalizePath}=require('../../out/core/paths');
 const store=new CoverageStore(),file=normalizePath('/Common.cs'),hashes=new Map([[file,'v1']]);
 const lines=Array.from({length:1000},(_,i)=>({line:i+1,hits:1}));
 const traces=Array.from({length:1000},(_,i)=>({groupId:`g${i}`,dependencies:[file],inputs:{[file]:'v1'},timestamp:1,reliable:true,coverage:[{file,hash:'v1',lines}]}));
 const live=new Set(traces.map(trace=>trace.groupId));await store.replaceAsync(traces,live);await store.summarizeAsync(hashes);store.markStale(live);
 // A changed positive contribution requires real aggregation work; freshness
 // changes alone can now reuse the warmed line cache. Other owners remain stale.
 await store.replaceAsync([{...traces[0],timestamp:2,coverage:[{file,hash:'v1',lines:[{line:1,hits:2},...lines.slice(1)]}]}],live);
 store.summary=()=>assert.fail('editor must not calculate synchronously');
 const proto=uiPrototype({Range:class{}}),calls=[];
 const editor={document:{uri:{fsPath:file},lineCount:1000,isDirty:false},setDecorations:(kind,lines)=>calls.push([kind,lines.length])};
 const context={config:{showCoverage:true},engine:{coverage:store,hashes},decorations:{covered:'covered',uncovered:'uncovered',stale:'stale'},lifetime:new AbortController()};
 const aggregation=store.summarizeAsync(hashes);let beats=0;const timer=setInterval(()=>beats++,1);
 try{await proto.decorate.call(context,[editor]);await aggregation;}finally{clearInterval(timer);}
 assert.ok(beats>0,'the editor path must let timers run');assert.deepEqual(calls,[['covered',0],['uncovered',0],['stale',1000]]);
 store.markStale(live);calls.length=0;context.engine.coverage={summarizeAsync:async(_hashes,signal)=>{await new Promise(resolve=>setImmediate(resolve));signal.throwIfAborted();return[];}};
 const pending=proto.decorate.call(context,[editor]);context.disposed=true;context.lifetime.abort();
 await assert.rejects(pending,{name:'AbortError'});assert.equal(calls.length,0,'disposing must prevent late editor writes');
});
