const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),io=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),vm=require('node:vm');
const {createRequire}=require('node:module');
const {setImmediate:turn}=require('node:timers/promises');
const {CoverageStore}=require('../../out/core/coverage');
const {SourceTracker}=require('../../out/services/sources');
const {OutputTail}=require('../../out/core/outputTail');
const {normalizePath,defaultExcludes}=require('../../out/core/paths');

function uiPrototype(vscode={},pathApi=path) {
 const file=path.resolve('out/extension.js'),realRequire=createRequire(file),exports={};
 vm.runInNewContext(fs.readFileSync(file,'utf8')+'\nexports.Testy=Testy;',{
  exports,require:name=>name==='vscode'?vscode:name==='./configuration'?{}:name==='node:path'?pathApi:realRequire(name),Buffer,setTimeout,clearTimeout
 });return exports.Testy.prototype;
}
async function temporary(t) {
 const root=normalizePath(await io.mkdtemp(path.join(os.tmpdir(),'testy-review7-')));t.after(()=>io.rm(root,{recursive:true,force:true}));return root;
}
function trace(groupId='a') {return {groupId,dependencies:['/code.cs'],inputs:{'/code.cs':'v1'},reliable:true,timestamp:1,coverage:[{file:'/code.cs',hash:'v1',lines:[{line:1,hits:1}]}]};}

test('transient coverage invalidation writes only changed contributions and preserves failed writes',async()=>{
 const store=new CoverageStore(),ids=new Set(['a','b']);store.replace([trace('a'),trace('b')],ids);store.takeDelta();
 const original=store.traces.get('b');
 store.markStale(ids);store.markStale(new Set(['b']),false);
 const delta=await store.takeDeltaAsync();assert.deepEqual(delta.traces.map(t=>t.groupId),['a']);assert.equal(store.traces.get('b'),original);
 store.markStale(new Set(['a']),false);store.markStale(new Set(['a']));assert.equal((await store.takeDeltaAsync()).traces.length,0,'returning to persisted stale state is also unchanged');
 store.replace([trace('b')],ids);store.markStale(new Set(['b']));store.markStale(new Set(['b']),false);
 assert.deepEqual(store.takeDelta().traces.map(t=>t.groupId),['b'],'a new contribution is still dirty after a transient toggle');
 store.markStale(new Set(['b']));const pending=store.takeDelta();store.markStale(new Set(['b']),false);
 store.retryDelta(pending);store.markStale(new Set(['b']));
 assert.deepEqual(store.takeDelta().traces.map(t=>t.groupId),['b'],'retry state must survive a toggle while a write is in flight');
 store.markStale(new Set(['a']),false);store.takeDelta();store.markStale(ids);store.invalidate(ids);store.markStale(ids,false);
 assert.equal(store.traces.get('a').reliable,false);assert.equal(store.takeDelta().traces.length,2,'reliability changes cannot be undone by freshness restoration');
 store.markHistorical(new Set(['a']));store.markStale(new Set(['a']),false);
 assert.equal(store.traces.get('a').historical,true);assert.equal(store.traces.get('a').stale,true);
});

test('large live coverage deltas yield, retain cancellation state and restart after concurrent invalidation',async()=>{
 const store=new CoverageStore(),sourceIds=Array.from({length:9000},(_,i)=>`s${i}`),ids=new Set(['a','b']);
 store.restorePacked(sourceIds.map((id,i)=>({id,file:`/s${i}.cs`,hash:'v1',lines:[1]})),[...ids].map(groupId=>({...trace(groupId),coverage:[],sourceIds})));
 store.markStale(ids,false);store.takeDelta();store.markStale(ids);
 const abort=new AbortController(),pending=store.takeDeltaAsync(abort.signal);await turn();abort.abort();
 await assert.rejects(pending,{name:'AbortError'});assert.equal(store.changedTraces.size,2);
 const next=store.takeDeltaAsync();await turn();store.markStale(new Set(['b']),false);
 const delta=await next;assert.deepEqual(delta.traces.map(t=>t.groupId),['a']);assert.equal(delta.sources.length,9000);
 assert.equal(store.changedTraces.size,0);
 const aggregate=store.summarizeAsync(new Map(sourceIds.map((_,i)=>[`/s${i}.cs`,'v1'])));
 await turn();store.markStale(new Set(['b']));const summaries=await aggregate;
 assert.equal(summaries.length,9000);assert.ok(summaries.every(s=>s.stale));
});

test('a full refresh supersedes generated-file event classification before deletion',async t=>{
 const root=await temporary(t),file=path.join(root,'Stamped.cs'),sources=new SourceTracker(),requests=[],proto=uiPrototype();
 sources.setFiles([file]);await io.writeFile(file,'// <auto-generated/>\nclass Stamped {}');
 const context={roots:[root],config:{pattern:'**/*.cs',excludes:[]},engine:{knownFiles:[file],sources,markChanged:async()=>{}},scheduler:{request:(...args)=>requests.push(args)}};
 const uri={scheme:'file',fsPath:file};await proto.changed.call(context,uri);await sources.refresh([file]);assert.equal(sources.isGenerated(file),true);
 await io.writeFile(file,'class Stamped {}');await sources.refresh([file]);assert.equal(sources.isGenerated(file),false);
 await io.rm(file);await proto.changed.call(context,uri,undefined,true);assert.equal(requests.length,1);
});

test('source refresh retains ignored semantic inputs and does not replace a newer event classification',async t=>{
 const root=await temporary(t),file=path.join(root,'Ignored.g.cs'),sources=new SourceTracker();
 await io.writeFile(file,'// <auto-generated/>\npartial class Hidden {}');sources.setFiles([], [file]);
 const read=io.readFile;let release,ready;
 const gate=new Promise(resolve=>release=resolve),started=new Promise(resolve=>ready=resolve);
 io.readFile=async(...args)=>{const bytes=await read(...args);if(args[0]===file){ready();await gate;}return bytes;};
 try {
  const refresh=sources.refresh([file]);await started;sources.observeGenerated(file,false);release();await refresh;
 }finally{io.readFile=read;release();}
 assert.equal(sources.isGenerated(file),false);assert.equal(sources.hashes.has(file),false);assert.ok(sources.analysisHashes.has(file));
 const previous=sources.analysisHashes.get(file);await io.writeFile(file,'partial class Hidden {}');await sources.refresh([file]);
 assert.notEqual(sources.analysisHashes.get(file),previous);assert.equal(sources.isGenerated(file),false);
 sources.setFiles([]);assert.equal(sources.classifications.has(file),false,'ordinary files leaving the graph need no retained tombstone');
});

test('directory-root exclusions cover create, rename and delete events while ordinary directories trigger',async t=>{
 const root=await temporary(t),proto=uiPrototype(),requests=[];
 const context={roots:[root],config:{pattern:'**/*.{cs,csproj}',excludes:[...defaultExcludes,'ignored/**']},engine:{knownFiles:[],markChanged:async()=>{}},scheduler:{request:(...args)=>requests.push(args)}};
 for(const name of ['bin','obj','.git','ignored']) {
  const file=path.join(root,name);await io.mkdir(file);const uri={scheme:'file',fsPath:file};
  await proto.changed.call(context,uri,undefined,true);await io.rm(file,{recursive:true});await proto.changed.call(context,uri,undefined,true);
 }
 assert.equal(requests.length,0);
 const ordinary=path.join(root,'Feature');await io.mkdir(ordinary);await proto.changed.call(context,{scheme:'file',fsPath:ordinary},undefined,true);
 context.engine.knownFiles=[path.join(ordinary,'Test.cs')];await io.rm(ordinary,{recursive:true});await proto.changed.call(context,{scheme:'file',fsPath:ordinary},undefined,true);
 assert.equal(requests.length,2);assert.ok(requests.every(([,full])=>full));
});

test('terminal result classification never resolves source paths',()=>{
 const {testResult,isTerminal,assertComplete}=require('../../out/services/mtp');
 const original=fs.realpathSync.native;let calls=0;fs.realpathSync.native=(...args)=>{calls++;return original(...args);};
 try {
  const nodes=Array.from({length:1000},(_,i)=>({uid:`t${i}`,'execution-state':'passed','location.file':__filename,'location.type':'Tests','location.method':`Case${i}`}));
  for(const node of nodes){assert.ok(isTerminal(node));assert.equal(testResult(node).fullyQualifiedName,`Tests.Case${node.uid.slice(1)}`);}
  assertComplete(nodes,nodes);assert.equal(calls,0);
 }finally{fs.realpathSync.native=original;}
});

test('output tails preserve the exact bounded suffix across trimming and compaction',()=>{
 for(const limit of [0,1,7,8192]) {
  const tail=new OutputTail(limit);let expected='';
  for(let i=0;i<5000;i++){const text=`${i}🌍`;expected=limit?(expected+text).slice(-limit):'';tail.append(text);}
  assert.equal(tail.text(),expected);
  const long='z'.repeat(10000);tail.append(long);assert.equal(tail.text(),limit?long.slice(-limit):'');
 }
});

test('process output decodes split UTF-8 and bounds both streams',async()=>{
 const {runProcess}=require('../../out/services/process');
 const script='const fs=require("node:fs");for(const fd of [1,2]){for(let i=0;i<144;i++)fs.writeSync(fd,Buffer.alloc(65536,fd===1?65:66));for(const byte of Buffer.from("🌍 end"))fs.writeSync(fd,Buffer.from([byte]));}';
 const result=await runProcess(process.execPath,['-e',script],{timeoutMs:10000});assert.equal(result.code,0);
 for(const [value,char] of [[result.stdout,'A'],[result.stderr,'B']]){assert.equal(value.length,8*1024*1024);assert.equal(value,char.repeat(8*1024*1024-'🌍 end'.length)+'🌍 end');}
});

test('tree refresh reuses unchanged children, updates locations and removes runtime results',async()=>{
 let replacements=0,created=0;
 function collection(){return{values:[],replace(values){replacements++;this.values=[...values];},add(value){this.values.push(value);}};}
 const proto=uiPrototype({Uri:{file:fsPath=>({fsPath})},Range:class{constructor(line){this.line=line;}}});
 const context={items:new Map(),testIds:new Map(),treeFiles:new Map(),treeProjects:new Map(),treeRoots:[],outcomes:new Map(),passed:0,failed:0,
  engine:{projects:[],knownTests:g=>g.tests},watch(){},updateStatus(){},setOutcome:proto.setOutcome,item:proto.item,
  controller:{items:collection(),createTestItem(id,label,uri){created++;return{id,label,uri,children:collection()};}}};
 const group={id:'g',project:'/Tests.csproj',framework:'net10.0',file:'/Tests.cs',tests:Array.from({length:2000},(_,i)=>({id:`t${i}`,name:`case ${i}`,file:'/Tests.cs',line:i+1}))};
 let completed=false;const first=proto.updateTree.call(context,[group]).then(()=>completed=true);await turn();assert.equal(completed,false,'large groups yield before publication completes');await first;
 const before=replacements,child=context.items.get('g:t0');await proto.updateTree.call(context,[group]);await proto.updateTree.call(context,[{...group,tests:group.tests.map(t=>({...t}))}]);
 assert.equal(replacements,before);assert.equal(context.items.get('g:t0'),child);
 const changed={...group,tests:[{...group.tests[0],name:'renamed',file:'/Moved.cs',line:9},...group.tests.slice(1)]};
 await proto.updateTree.call(context,[changed]);assert.equal(replacements,before+1);assert.equal(context.items.get('g:t0').uri.fsPath,'/Moved.cs');assert.equal(context.items.get('g:t0').range.line,8);
 proto.publishResult.call(context,changed,{id:'runtime',name:'runtime',outcome:'passed'});assert.equal(context.passed,1);
 await proto.updateTree.call(context,[changed]);assert.equal(context.items.has('g:runtime'),false);assert.equal(context.passed,0);
 proto.publishResult.call(context,changed,{id:'runtime2',name:'runtime2',outcome:'passed'});
 await proto.updateTree.call(context,[]);assert.equal(context.items.size,0);assert.equal(context.testIds.size,0);assert.equal(context.passed,0);assert.ok(created>=2000);
});

test('tree items reuse Windows URI paths with native separators',()=>{
 let created=0;
 const proto=uiPrototype({Uri:{file:file=>({fsPath:path.win32.normalize(file)})}},path.win32);
 const context={items:new Map(),controller:{createTestItem(id,label,uri){created++;return{id,label,uri};}}};
 const original=proto.item.call(context,'case','case','c:/workspace/Tests.cs');
 assert.equal(original.uri.fsPath,'c:\\workspace\\Tests.cs');
 assert.equal(proto.item.call(context,'case','renamed','c:/workspace/Tests.cs'),original);assert.equal(original.label,'renamed');assert.equal(created,1);
 assert.notEqual(proto.item.call(context,'case','renamed','c:/workspace/Moved.cs'),original);assert.equal(created,2);
});
