
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {SourceTracker}=require('../../out/services/sources');
const {normalizePath}=require('../../out/core/paths');
test('handwritten code containing generator marker strings must remain tracked',async t=>{
 const root=normalizePath(await fs.mkdtemp(path.join(os.tmpdir(),'testy-review9-marker-')));t.after(()=>fs.rm(root,{recursive:true,force:true}));
 const source=path.join(root,'GeneratorTests.cs'),content='public class GeneratorTests { public string ExpectedHeader() => "<auto-generated/>"; }';
 await fs.writeFile(source,content);
 const sources=new SourceTracker();sources.setFiles([source]);await sources.refresh([source]);
 const file=path.resolve('out/extension.js'),exports={},realRequire=require('node:module').createRequire(file);
 require('node:vm').runInNewContext((await fs.readFile(file,'utf8'))+'\nexports.Testy=Testy;',{
  exports,require:name=>name==='vscode'?{}:name==='./configuration'?{}:realRequire(name),Buffer,setTimeout,clearTimeout
 });
 const requests=[];
 const context={disposed:false,roots:[root],config:{excludes:[],pattern:'**/*.cs'},scheduler:{request:(...args)=>requests.push(args)},
  engine:{knownFiles:[source],directories:[root],sources,markChanged:async()=>{}}};
 await exports.Testy.prototype.changed.call(context,{scheme:'file',fsPath:source},content);
 assert.equal(sources.hashes.has(source),true,'a string literal must not exclude handwritten input');
 assert.equal(requests.length,1);
});

test('generated headers are leading comment declarations, not marker examples or literals',()=>{
 const {isGeneratedSource}=require('../../out/core/paths');
 const headers=['// <auto-generated/>','\ufeff\n// Copyright\n// <AUTO-GENERATED>\n// Tool output',
  '/*\n * <auto-generated/>\n */\nclass C {}','/// <auto-generated/>'];
 const ordinary=['public class C { public string Header => "<auto-generated/>"; }',
  '// Detects <auto-generated> markers.\nclass C {}', '/* An example: <auto-generated/> */',
  'class C {}\n// <auto-generated/>', 'const string Expected = """\n// <auto-generated/>\n""";'];
 for(const content of headers)assert.equal(isGeneratedSource('/Code.cs',content),true,content);
 for(const content of ordinary)assert.equal(isGeneratedSource('/Code.cs',content),false,content);
});

test('a formerly absent build dependency invalidates retained coverage when created',()=>{
 const {CoverageStore}=require('../../out/core/coverage'),{sourceVersion}=require('../../out/core/paths');
 const store=new CoverageStore(),initial=new Map([['/Code.cs','code']]);
 store.replace([{groupId:'file',dependencies:['/Code.cs','/.editorconfig'],inputs:{'/Code.cs':'code','/.editorconfig':sourceVersion(initial,'/.editorconfig')},
  coverage:[{file:'/Code.cs',hash:'code',lines:[{line:1,hits:1}]}],reliable:true,timestamp:0}],new Set(['file']));
 assert.equal(store.summarize(initial)[0].stale,false);
 assert.equal(store.summarize(new Map([...initial,['/.editorconfig','new']]))[0].stale,true);
});

test('inherited compiler config watchers do not watch ancestors recursively or accept unrelated saves',async()=>{
 const file=path.resolve('out/extension.js'),exports={},realRequire=require('node:module').createRequire(file),patterns=[];
 const vscode={RelativePattern:class {constructor(base,pattern){Object.assign(this,{base,pattern});}},workspace:{createFileSystemWatcher(pattern){
  patterns.push(pattern);return{dispose(){},onDidChange(){},onDidCreate(){},onDidDelete(){}};
 }}};
 require('node:vm').runInNewContext((await fs.readFile(file,'utf8'))+'\nexports.Testy=Testy;',{
  exports,require:name=>name==='vscode'?vscode:name==='./configuration'?{}:realRequire(name),Buffer,setTimeout,clearTimeout
 });
 const requests=[],context={roots:['/workspace'],watchers:[],config:{trigger:'fileSystem',excludes:[],pattern:require('../../package.json').contributes.configuration.properties['testy.fileWatcherPattern'].default},
  engine:{inputVersion:1,knownFiles:['/.editorconfig','/workspace/Tests.cs'],directories:['/','/workspace'],markChanged:async()=>{}},scheduler:{request:(...args)=>requests.push(args)}};
 exports.Testy.prototype.watch.call(context);
 assert.equal(patterns.some(p=>p.base==='/'&&p.pattern.includes('**')),false);
 assert.ok(patterns.some(p=>p.base==='/'&&p.pattern==='*'));
 await exports.Testy.prototype.changed.call(context,{scheme:'file',fsPath:'/elsewhere/Unrelated.cs'},'class Unrelated {}');assert.equal(requests.length,0);
 await exports.Testy.prototype.changed.call(context,{scheme:'file',fsPath:'/.editorconfig'},'root = true');assert.equal(requests.length,1);
});

test('runtime module reports distinguish instrumented, external and in-memory loads, and require completion',async t=>{
 const {RuntimeObservation}=require('../../out/services/runtimeObservation');
 const directory=await fs.mkdtemp(path.join(os.tmpdir(),'testy-observer-'));t.after(()=>fs.rm(directory,{recursive:true,force:true}));
 const assembly=normalizePath(path.join(directory,'Tests.dll')),instrumented=normalizePath(path.join(directory,'Plugin.dll'));
 const observer=await RuntimeObservation.start(path.join(directory,'reports'),assembly,[
  {name:'Plugin',project:'/Plugin.csproj',sources:['/Plugin.cs']},{name:'plugin',project:'/Alternative.csproj',sources:['/Alternative.cs']}
 ],[instrumented],{DOTNET_STARTUP_HOOKS:'/existing/hook.dll'});
 assert.ok(observer.env.DOTNET_STARTUP_HOOKS.endsWith(path.delimiter+'/existing/hook.dll'));
 const encode=s=>Buffer.from(s).toString('base64'),report=path.join(directory,'reports','host.log');
 const lines=location=>`ready\t${encode(assembly)}\r\nmodule\t${encode('Plugin')}\t${encode(location)}\r\ncomplete\ttrue\r\n`;
 await fs.writeFile(report,lines(instrumented));assert.deepEqual(await observer.dependencies(),{files:[],projects:[]});
 for(const location of ['/original/Plugin.dll','']){
  await fs.writeFile(report,lines(location));const observed=await observer.dependencies();
  assert.deepEqual(new Set(observed.files),new Set(['/Plugin.cs','/Alternative.cs']));assert.deepEqual(new Set(observed.projects),new Set(['/Plugin.csproj','/Alternative.csproj']));
 }
 await fs.writeFile(path.join(directory,'reports','child.log'),`ready\t${encode('/Child.dll')}\n`);
 await assert.rejects(observer.dependencies(),/incomplete/);await fs.rm(path.join(directory,'reports','child.log'));
 await fs.writeFile(report,lines(instrumented).replace('complete\ttrue','complete\tfalse'));await assert.rejects(observer.dependencies(),/incomplete/);
 await fs.writeFile(report,lines(instrumented).replace(encode(assembly),encode('/Collector.dll')));await assert.rejects(observer.dependencies(),/test host/);
 await fs.writeFile(report,lines(instrumented).replace(encode('Plugin'),'invalid!'));await assert.rejects(observer.dependencies(),/Invalid/);
});

test('module dependencies cover new source files across projects and survive cache restoration',async t=>{
 const {CoverageStore}=require('../../out/core/coverage'),{CoverageCache}=require('../../out/services/cache'),{selectTests,ProjectIndex}=require('../../out/core/selection');
 const directory=await fs.mkdtemp(path.join(os.tmpdir(),'testy-module-cache-'));t.after(()=>fs.rm(directory,{recursive:true,force:true}));
 const projects=[{file:'/Plugin/Plugin.csproj',assembly:'/Plugin.dll',sourceFiles:['/Plugin/Old.cs'],references:[]},
  {file:'/Tests/Tests.csproj',assembly:'/Tests.dll',sourceFiles:['/Tests/Dynamic.cs'],references:[]}];
 const groups=[{id:'dynamic',project:'/Tests/Tests.csproj',file:'/Tests/Dynamic.cs'}];
 const trace={groupId:'dynamic',moduleProjects:['/Plugin/Plugin.csproj'],dependencies:['/Plugin/Old.cs'],inputs:{},coverage:[],reliable:true,timestamp:0};
 const store=new CoverageStore();store.replace([trace],new Set(['dynamic']));
 const selected=store=>selectTests(groups,projects,store.traces,['/Plugin/New.cs'],'affected',false,new Set(),new ProjectIndex(projects),file=>store.dependentGroups([file]),project=>store.dependentProjects([project]));
 assert.equal(selected(store).groups.length,1);
 const cache=new CoverageCache(directory,()=>{});await cache.save(store.takeDelta());const restored=new CoverageStore();await cache.restore(restored);
 assert.deepEqual([...restored.dependentProjects(['/Plugin/Plugin.csproj'])],['dynamic']);assert.equal(selected(restored).groups.length,1);
 restored.replace([{...trace,moduleProjects:[]}],new Set(['dynamic']));assert.equal(restored.dependentProjects(['/Plugin/Plugin.csproj']).size,0);
});
