const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {isGeneratedSource,sourceText,normalizePath}=require('../../out/core/paths');
const {SourceTracker}=require('../../out/services/sources');

const encodings={
 utf8:text=>Buffer.from(text),
 utf8bom:text=>Buffer.concat([Buffer.from([0xef,0xbb,0xbf]),Buffer.from(text)]),
 utf16le:text=>Buffer.concat([Buffer.from([0xff,0xfe]),Buffer.from(text,'utf16le')]),
 utf16be:text=>Buffer.concat([Buffer.from([0xfe,0xff]),Buffer.from(text,'utf16le').swap16()])
};

test('generated headers decode UTF-8 and both UTF-16 BOMs within the same byte limit',()=>{
 const text='// Copyright ©\r\n// <auto-generated/>\r\nclass Generated {}';
 for(const [name,encode] of Object.entries(encodings)){
  const bytes=encode(text),before=Buffer.from(bytes);
  assert.equal(sourceText(bytes),text,name);assert.equal(isGeneratedSource('/Generated.cs',bytes),true,name);assert.deepEqual(bytes,before);
  assert.equal(isGeneratedSource('/Ordinary.cs',encode('class C { string Header => "<auto-generated/>"; }')),false,name);
  assert.equal(isGeneratedSource('/Late.cs',encode(' '.repeat(2050)+'// <auto-generated/>')),false,name);
  const prefix=encode(' '.repeat(1100)+'// <auto-generated/>');
  assert.equal(isGeneratedSource('/Boundary.cs',prefix),!name.startsWith('utf16'),`${name}: bytes, not character count`);
 }
 const odd=Buffer.concat([encodings.utf16be(text),Buffer.from([0])]);
 assert.equal(sourceText(odd),text,'a partial final code unit is ignored');
});

test('UTF-16 generated inputs retain analysis aliases without entering tracked hashes',async t=>{
 const root=normalizePath(await fs.mkdtemp(path.join(os.tmpdir(),'testy-encoded-sources-')));t.after(()=>fs.rm(root,{recursive:true,force:true}));
 const file=path.join(root,'Generated.cs'),sources=new SourceTracker();sources.setFiles([file]);
 const alias='global using IgnoreCoverage = System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute;';
 for(const encode of [encodings.utf16le,encodings.utf16be]){
  await fs.writeFile(file,encode('// <auto-generated/>\n'+alias));await sources.refresh([file]);
  assert.equal(sources.isGenerated(file),true);assert.equal(sources.hashes.has(file),false);
  assert.ok(sources.analysisHashes.has(file));assert.ok(sources.aliasSources.get(file).includes(alias));
  await fs.writeFile(file,encode(alias+'\nclass Ordinary {}'));await sources.refresh([file]);
  assert.equal(sources.isGenerated(file),false);assert.ok(sources.hashes.has(file));
 }
});

function editor(config={}) {
 const disposable=()=>({dispose(){}}),invalidated=[],patterns=[],handlers={};
 const controller={...disposable(),createRunProfile:()=>({}),invalidateTestResults:items=>invalidated.push(...items.map(item=>item.id))};
 const vscode={tests:{createTestController:()=>controller},TestRunProfileKind:{Run:1,Coverage:3},StatusBarAlignment:{Left:1},
  ThemeColor:class {},RelativePattern:class {constructor(base,pattern){Object.assign(this,{base,pattern});}},Uri:{joinPath:()=>({})},
  commands:{registerCommand:disposable,executeCommand:async()=>{}},
  window:{visibleTextEditors:[],createOutputChannel:()=>({...disposable(),append(){},appendLine(){}}),createStatusBarItem:()=>({...disposable(),show(){}}),
   createTextEditorDecorationType:disposable,onDidChangeVisibleTextEditors:disposable},
  workspace:{onDidSaveTextDocument:callback=>{handlers.save=callback;return disposable();},onDidDeleteFiles:disposable,onDidRenameFiles:disposable,
   onDidChangeConfiguration:disposable,onDidChangeWorkspaceFolders:disposable,onDidChangeTextDocument:disposable,
   createFileSystemWatcher:pattern=>{patterns.push(pattern);return {...disposable(),onDidChange(){},onDidCreate(){},onDidDelete(){}};}}
 };
 const file=path.resolve('out/extension.js'),exports={},real=require('node:module').createRequire(file);
 require('node:vm').runInNewContext(require('node:fs').readFileSync(file,'utf8')+'\nexports.Testy=Testy;',{
  exports,require:name=>name==='vscode'?vscode:name==='./configuration'?{configuration:()=>({enabled:true,trigger:'save',showCoverage:false,debounce:100,
   pattern:require('../../package.json').contributes.configuration.properties['testy.fileWatcherPattern'].default,excludes:[],...config})}:real(name),Buffer,setTimeout,clearTimeout,AbortController
 });
 const ui=new exports.Testy({extensionUri:{},storageUri:{fsPath:os.tmpdir()},globalStorageUri:{fsPath:os.tmpdir()},extensionPath:process.cwd()},['/workspace']);
 return {ui,invalidated,patterns,handlers};
}

test('manual leaf results preserve unselected runtime failures until those rows actually rerun',t=>{
 const {selectManual}=require('../../out/services/engine'),{ui,invalidated}=editor();t.after(()=>ui.dispose());
 const node=id=>({id,name:id,node:{uid:id},line:1}),ordinary=node('ordinary'),row=node('deferred-failure');
 const group={id:'file-id',project:'/workspace/Tests.csproj',framework:'net10.0',file:'/workspace/Tests.cs',tests:[ordinary]};
 ui.engine.groups=[group];ui.engine.runtime.set(group.id,new Map([[row.id,row]]));
 for(const test of [ordinary,row])ui.items.set(`${group.id}:${test.id}`,{id:`${group.id}:${test.id}`});
 ui.setOutcome(`${group.id}:${ordinary.id}`,'passed');ui.setOutcome(`${group.id}:${row.id}`,'failed');
 const groups=selectManual([group],{groups:new Set([group.id]),tests:new Map([[group.id,new Set([ordinary.id])]])},g=>ui.engine.knownTests(g));
 ui.engine.options.events.selected({groups,reason:'Manual run',fallback:false});
 ui.publishResult(group,{id:ordinary.id,name:ordinary.name,outcome:'passed',duration:0});
 assert.deepEqual(invalidated,[`${group.id}:${ordinary.id}`]);assert.equal(ui.outcomes.get(`${group.id}:${row.id}`),'failed');assert.equal(ui.failed,1);
 ui.engine.options.events.selected({groups:[group],reason:'Containing file',fallback:true});
 assert.equal(ui.outcomes.get(`${group.id}:${row.id}`),'failed','a discovered parent does not prove the deferred row will run');
 ui.publishResult(group,{id:row.id,name:row.name,outcome:'passed',duration:0});assert.equal(ui.failed,0);
});

test('editor disk classification observes UTF-16 saves, header removal and generated deletion',async t=>{
 const root=normalizePath(await fs.mkdtemp(path.join(os.tmpdir(),'testy-encoded-events-')));t.after(()=>fs.rm(root,{recursive:true,force:true}));
 const {ui,handlers}=editor();t.after(()=>ui.dispose());ui.roots=[root];
 const requests=[];ui.scheduler.request=(...args)=>requests.push(args);ui.engine.markChanged=async()=>{};
 const file=normalizePath(path.join(root,'Generated.cs')),uri={scheme:'file',fsPath:file};
 for(const encode of [encodings.utf16le,encodings.utf16be]){
  await fs.writeFile(file,encode('// <auto-generated/>\n'));
  // Exercise the real save callback, then await its asynchronous disk handler.
  let saved;const changed=ui.changed.bind(ui);ui.changed=(...args)=>saved=changed(...args);
  handlers.save({uri,getText:()=>{throw new Error('The byte prefix must come from the saved encoding.');}});await saved;ui.changed=changed;
  assert.equal(requests.length,0);assert.equal(ui.engine.sources.isGenerated(file),true);
  await fs.rm(file);await ui.changed(uri,undefined,true);assert.equal(requests.length,0);
 }
 await fs.writeFile(file,encodings.utf16be('class C { string Header => "<auto-generated/>"; }'));await ui.changed(uri);
 assert.equal(requests.length,1);assert.equal(ui.engine.sources.isGenerated(file),false);
});

test('inherited SDK candidates use bounded watchers and ignore unrelated external saves',async t=>{
 const {sdkConfigurationFiles}=require('../../out/services/projects'),{ui,patterns}=editor({trigger:'fileSystem'});t.after(()=>ui.dispose());
 const root=normalizePath(path.parse(process.cwd()).root),workspace=normalizePath(path.join(root,'workspace')),global=normalizePath(path.join(root,'global.json'));ui.roots=[workspace];
 const candidates=sdkConfigurationFiles(path.join(workspace,'Tests','Tests.csproj'));
 assert.ok(candidates.includes(global));assert.ok(candidates.includes(normalizePath(path.join(workspace,'Tests','global.json'))));
 ui.engine.setInputs([...candidates,path.join(workspace,'Tests.cs')]);
 assert.equal(patterns.some(p=>p.base===root&&p.pattern.includes('**')),false);assert.ok(patterns.some(p=>p.base===root&&p.pattern==='*'));
 const requests=[];ui.scheduler.request=(...args)=>requests.push(args);ui.engine.markChanged=async()=>{};
 await ui.changed({scheme:'file',fsPath:path.join(root,'elsewhere','Unrelated.cs')},'class C {}');assert.equal(requests.length,0);
 await ui.changed({scheme:'file',fsPath:global},'{}');assert.equal(requests.length,1);
 const count=patterns.length;ui.engine.setInputs([...candidates,path.join(workspace,'Tests.cs')]);assert.equal(patterns.length,count,'unchanged inputs preserve watchers');
});

test('bundled managed assemblies contain portable IL rather than build-machine native code',async()=>{
 const directories=[path.resolve(process.env.TESTY_DIST??'dist')],files=[];
 while(directories.length){const directory=directories.pop();for(const entry of await fs.readdir(directory,{withFileTypes:true})){
  const file=path.join(directory,entry.name);if(entry.isDirectory())directories.push(file);else if(entry.name.endsWith('.dll'))files.push(file);
 }}
 assert.ok(files.some(file=>file.endsWith('Microsoft.CodeAnalysis.CSharp.dll')));
 // PE/COFF headers and IMAGE_COR20_HEADER, as defined by Microsoft's PE
 // specification and dotnet/runtime's corhdr.h. AnyCPU IL uses I386 without
 // 32BITREQUIRED; a ManagedNativeHeader would reintroduce platform-specific code.
 for(const file of files){
  const bytes=await fs.readFile(file),pe=bytes.readUInt32LE(0x3c);
  assert.equal(bytes.toString('ascii',pe,pe+4),'PE\0\0',file);
  assert.equal(bytes.readUInt16LE(pe+4),0x14c,`${file}: use portable packages, not native SDK binaries`);
  const optional=pe+24;assert.equal(bytes.readUInt16LE(optional),0x10b,file);
  const rva=bytes.readUInt32LE(optional+96+14*8),count=bytes.readUInt16LE(pe+6),sections=optional+bytes.readUInt16LE(pe+20);
  let header;
  for(let index=0;index<count;index++){
   const section=sections+index*40,start=bytes.readUInt32LE(section+12),size=bytes.readUInt32LE(section+16);
   if(rva>=start&&rva<start+size)header=bytes.readUInt32LE(section+20)+rva-start;
  }
  assert.notEqual(header,undefined,file);assert.equal(bytes.readUInt32LE(header+16)&3,1,`${file}: ILONLY without 32BITREQUIRED`);
  assert.equal(bytes.readUInt32LE(header+64),0,`${file}: no native managed image`);assert.equal(bytes.readUInt32LE(header+68),0,file);
 }
});
